# Generated by Django 2.2.7 on 2022-01-12 17:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_contractor', models.BooleanField(default=False)),
                ('is_officer', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bmc_officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Appuser')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bmc_officers', to='common.Ward')),
            ],
            options={
                'db_table': 'bmc_officers',
            },
        ),
        migrations.CreateModel(
            name='Bmc_contractor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Appuser')),
                ('company_name', models.CharField(max_length=50)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bmc_contractors', to='common.Ward')),
            ],
            options={
                'db_table': 'bmc_contractors',
            },
        ),
    ]
