# Generated by Django 2.2.7 on 2022-01-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220113_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmc_contractor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Appuser'),
        ),
    ]
