# Generated by Django 2.2.7 on 2020-09-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracklog_history',
            name='digital_io_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
