# Generated by Django 2.2.7 on 2021-10-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200927_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracklog_history',
            options={'ordering': ['vehicle', 'datetime']},
        ),
        migrations.RenameField(
            model_name='tracklog_history',
            old_name='digital_io_status',
            new_name='dio',
        ),
        migrations.RenameField(
            model_name='tracklog_history',
            old_name='emergency_status',
            new_name='emergency',
        ),
        migrations.RenameField(
            model_name='tracklog_history',
            old_name='ignition_status',
            new_name='ignition',
        ),
        migrations.AddField(
            model_name='tracklog_history',
            name='dod',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tracklog_history',
            name='shift',
            field=models.CharField(choices=[('1', 'Morning'), ('2', 'Afternoon'), ('3', 'Night')], default='1', max_length=1),
        ),
    ]
