# Generated by Django 2.2.7 on 2021-10-18 12:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0009_auto_20211018_1635'),
        ('reports', '0004_auto_20211018_1615'),
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='Current_tracklog_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('speed', models.FloatField(blank=True, default=0.0)),
                ('heading', models.IntegerField(blank=True, null=True)),
                ('mps', models.BooleanField(default=0, null=True)),
                ('miv', models.FloatField(blank=True, default=0.0)),
                ('ibv', models.FloatField(blank=True, default=0.0)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('ignition', models.BooleanField(default=1)),
                ('emergency', models.CharField(blank=True, max_length=4, null=True)),
                ('dio', models.CharField(blank=True, max_length=150, null=True)),
                ('dod', models.DateField(auto_now=True, null=True)),
                ('shift', models.CharField(choices=[('1', 'Morning'), ('2', 'Afternoon'), ('3', 'Night')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'current_tracklog_historys',
                'ordering': ['vehicle', 'datetime'],
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod('list'),
                'key': ['shift'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='Current_tracklog_history',
            name='default',
        ),
        migrations.AddField(
            model_name='current_tracklog_history',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_tracklog_historys', to='swmadmin.Vehicle'),
        ),
    ]
