# Generated by Django 2.2.7 on 2021-10-18 12:19

from psqlextra.backend.migrations.operations import PostgresAddListPartition
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20211018_1742'),
    ]

    operations = [
        PostgresAddListPartition(
           model_name="Current_tracklog_history",
           name="1",
           values=["1"],
        ),
        PostgresAddListPartition(
           model_name="Current_tracklog_history",
           name="2",
           values=["2"],
        ),
        PostgresAddListPartition(
           model_name="Current_tracklog_history",
           name="3",
           values=["3"],
        ),
    ]
