# Generated by Django 2.2.7 on 2022-01-15 22:58

from django.db import migrations,models

from psqlextra.backend.migrations.operations import PostgresDeleteRangePartition

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20211023_0008'),
    ]

    operations = [
        PostgresDeleteRangePartition(
            model_name="Vehicle_tracklog_history",
            name="1_2_2002",
        ),
    ]
