# Generated by Django 2.2.7 on 2022-01-15 23:08

from django.db import migrations,models

from psqlextra.backend.migrations.operations import PostgresDeleteRangePartition


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20220115_2258'),
    ]

    operations = [
        PostgresDeleteRangePartition(
            model_name="Vehicle_tracklog_history",
            name="3_4_2002",
        ),
        PostgresDeleteRangePartition(
            model_name="Vehicle_tracklog_history",
            name="5_6_2002",
        ),
        PostgresDeleteRangePartition(
            model_name="Vehicle_tracklog_history",
            name="7_8_2002",
        ),
        PostgresDeleteRangePartition(
            model_name="Vehicle_tracklog_history",
            name="9_10_2002",
        ),
        PostgresDeleteRangePartition(
            model_name="Vehicle_tracklog_history",
            name="11_12_2002",
        ),
    ]
