# Generated by Django 2.2.7 on 2022-01-16 13:08

from django.db import migrations
from psqlextra.backend.migrations.operations import PostgresAddRangePartition

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20220115_2308'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="1_2_2022",
            from_values='2022-01-01 05:55:01',
            to_values='2022-03-01 05:55:00',
        ),
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="3_4_2022",
            from_values='2022-03-01 05:55:01',
            to_values='2022-05-01 05:55:00',
        ),
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="5_6_2022",
            from_values='2022-05-01 05:55:01',
            to_values='2022-07-01 05:55:00',
        ),
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="7_8_2022",
            from_values='2022-07-01 05:55:01',
            to_values='2022-09-01 05:55:00',
        ),
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="9_10_2022",
            from_values='2022-09-01 05:55:01',
            to_values='2022-11-01 05:55:00',
        ),
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="11_12_2022",
            from_values='2022-11-01 05:55:01',
            to_values='2023-01-01 05:55:00',
        ),
    ]
