# Generated by Django 2.2.7 on 2022-01-17 23:28
from psqlextra.backend.migrations.operations import PostgresAddListPartition
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20220117_2324'),
    ]

    operations = [
        PostgresAddListPartition(
           model_name="Live_tracklog_history",
           name="1",
           values=["1"],
        ),
        PostgresAddListPartition(
           model_name="Live_tracklog_history",
           name="2",
           values=["2"],
        ),
        PostgresAddListPartition(
           model_name="Live_tracklog_history",
           name="3",
           values=["3"],
        ),
    ]
