# Generated by Django 2.2.7 on 2022-01-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20220117_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faulty_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'faulty_records',
                'ordering': ['created_at'],
            },
        ),
    ]
