# Generated by Django 2.2.7 on 2022-12-30 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('swmadmin', '0018_auto_20220715_1725'),
        ('reports', '0016_unlogged_tracklog_history_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('1', '6am-2pm'), ('2', '2pm-10pm'), ('3', '10pm-6am')], default='1', max_length=1)),
                ('route_code', models.CharField(max_length=20, unique=True)),
                ('route_name', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swmadmin.Vehicle')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_allocation_2', to='common.Ward')),
            ],
            options={
                'db_table': 'route_allocation',
            },
        ),
    ]
