# Generated by Django 2.2.7 on 2023-01-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_route_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_allocation',
            name='route_code',
            field=models.CharField(max_length=20),
        ),
    ]
