# Generated by Django 2.2.7 on 2023-01-12 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('reports', '0018_auto_20230102_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpdesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('query', models.CharField(max_length=1000)),
                ('action', models.CharField(max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='helpdesk', to='common.Ward')),
            ],
            options={
                'db_table': 'helpdesk',
            },
        ),
    ]
