# Generated by Django 2.2.7 on 2023-02-16 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0019_helpdesk'),
    ]

    operations = [
        migrations.CreateModel(
            name='route_compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=20)),
                ('bin_location', models.CharField(max_length=100)),
                ('bin_geofence', models.CharField(max_length=1000)),
                ('route_name', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('route_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bin_data', to='reports.Route_Allocation')),
            ],
            options={
                'db_table': 'route_compliance',
            },
        ),
    ]
