# Generated by Django 2.2.7 on 2023-02-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_route_compliance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route_compliance',
            old_name='route_name',
            new_name='bin_name',
        ),
    ]
