# Generated by Django 2.2.7 on 2023-02-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20230216_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route_compliance',
            name='bin_geofence',
        ),
    ]
