# Generated by Django 2.2.7 on 2023-02-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_remove_route_compliance_bin_geofence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route_compliance',
            name='bin_name',
        ),
    ]
