# Generated by Django 2.2.7 on 2023-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_remove_route_compliance_bin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_compliance',
            name='bin_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
