# Generated by Django 2.2.7 on 2023-03-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('reports', '0024_route_compliance_bin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_compliance',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_compliance', to='common.Ward'),
        ),
    ]
