# Generated by Django 2.2.7 on 2023-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_route_compliance_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_compliance',
            name='bin_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
