# Generated by Django 2.2.7 on 2023-03-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_auto_20230304_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_allocation',
            name='bin_count',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
