# Generated by Django 2.2.7 on 2023-04-18 11:51

from psqlextra.backend.migrations.operations import PostgresAddRangePartition
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_route_allocation_bin_count'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="9_10_2023",
            from_values='2023-09-01 05:55:01',
            to_values='2023-11-01 05:55:00',
        ),
    ]


