# Generated by Django 2.2.7 on 2023-04-18 12:20

from psqlextra.backend.migrations.operations import PostgresAddRangePartition
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_auto_20230418_1151'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="5_6_2023",
            from_values='2023-05-01 05:55:01',
            to_values='2023-07-01 05:55:00',
        ),
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="7_8_2023",
            from_values='2023-07-01 05:55:01',
            to_values='2023-09-01 05:55:00',
        ),
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="11_12_2023",
            from_values='2023-11-01 05:55:01',
            to_values='2024-01-01 05:55:00',
        ),
    ]
