# Generated by Django 2.2.7 on 2023-04-18 12:42

from psqlextra.backend.migrations.operations import PostgresAddRangePartition
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_auto_20230418_1220'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="Vehicle_tracklog_history",
            name="1_2_2024",
            from_values='2024-01-01 05:55:01',
            to_values='2024-03-01 05:55:00',
        ),
    ]
