# Generated by Django 2.2.7 on 2023-04-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_auto_20230418_1242'),
    ]

    operations = [
    ]
