# Generated by Django 2.2.7 on 2023-04-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_auto_20230428_1759'),
    ]

    operations = [
    ]
