# Generated by Django 2.2.7 on 2023-07-07 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('reports', '0032_auto_20230428_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_Compliance_Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=20, null=True)),
                ('bin_location', models.CharField(max_length=100)),
                ('route_code', models.CharField(max_length=100)),
                ('bin_name', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_compliance_demo', to='common.Ward')),
            ],
            options={
                'db_table': 'route_compliance_demo',
            },
        ),
    ]
