# Generated by Django 2.2.7 on 2023-07-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_route_compliance_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route_compliance_demo',
            name='bin_code',
        ),
        migrations.RemoveField(
            model_name='route_compliance_demo',
            name='bin_location',
        ),
        migrations.RemoveField(
            model_name='route_compliance_demo',
            name='bin_name',
        ),
        migrations.RemoveField(
            model_name='route_compliance_demo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='route_compliance_demo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='route_compliance_demo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='route_compliance_demo',
            name='route_code',
        ),
        migrations.RemoveField(
            model_name='route_compliance_demo',
            name='ward',
        ),
        migrations.AlterModelTable(
            name='route_compliance_demo',
            table=None,
        ),
    ]
