# Generated by Django 2.2.7 on 2023-07-07 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('reports', '0034_auto_20230707_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_compliance_demo',
            name='bin_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route_compliance_demo',
            name='bin_location',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='route_compliance_demo',
            name='bin_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='route_compliance_demo',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='route_compliance_demo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='route_compliance_demo',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='route_compliance_demo',
            name='route_code',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='route_compliance_demo',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_compliance_demo', to='common.Ward'),
        ),
        migrations.AlterModelTable(
            name='route_compliance_demo',
            table='route_compliance_demo',
        ),
    ]
