# Generated by Django 2.2.7 on 2020-09-01 15:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contractors',
            },
        ),
        migrations.CreateModel(
            name='Halt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('route_fence', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='common.Ward')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('mc', 'Mini Compactor'), ('lc', 'Large Compactor'), ('swm', 'Sweeper Vehicle Machine'), ('scv', 'Small Compactor Vehicle'), ('sl', 'Sleeper Vehicle')], default='scv', max_length=10)),
                ('engine_number', models.CharField(max_length=20, unique=True)),
                ('chassis_number', models.CharField(max_length=20, unique=True)),
                ('maker', models.CharField(max_length=20)),
                ('manufactured_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swmadmin.Contractor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Stop_station',
            fields=[
                ('halt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='swmadmin.Halt')),
                ('is_mlc', models.BooleanField(default=0, verbose_name='MLC')),
                ('is_chkpst', models.BooleanField(default=0, verbose_name='CHECKPOST')),
                ('is_tnsstn', models.BooleanField(default=0, verbose_name='TRANSFER STATION')),
                ('is_dmpgnd', models.BooleanField(default=0, verbose_name='DUMPING GROUND')),
                ('is_garage', models.BooleanField(default=0, verbose_name='GARAGE')),
                ('stop_station_fence', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'stop_stations',
            },
            bases=('swmadmin.halt',),
        ),
        migrations.CreateModel(
            name='Ward_Contractor_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('contractor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='swmadmin.Contractor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('ward', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Ward')),
            ],
            options={
                'db_table': 'ward_contractor_mapping',
            },
        ),
        migrations.CreateModel(
            name='Route_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('shift', models.CharField(choices=[('1', 'Morning'), ('2', 'Afternoon'), ('3', 'Night')], default=1, max_length=1)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_schedules', to='swmadmin.Route')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_schedules', to='swmadmin.Vehicle')),
            ],
            options={
                'db_table': 'route_schedules',
            },
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=25, unique=True)),
                ('sim', models.CharField(max_length=20, unique=True)),
                ('wnld_tag', models.CharField(max_length=30, null=True, unique=True)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swmadmin.Vehicle')),
            ],
            options={
                'db_table': 'installations',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Garage_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='swmadmin.Vehicle')),
                ('garage', models.ForeignKey(limit_choices_to={'is_garage': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='swmadmin.Stop_station')),
            ],
            options={
                'db_table': 'vehicle_garage_mapping',
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('halt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='swmadmin.Halt')),
                ('code', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('bin_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('bin_fence', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='swmadmin.Route')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='common.Ward')),
            ],
            options={
                'db_table': 'bins',
                'ordering': ['code'],
            },
            bases=('swmadmin.halt',),
        ),
    ]
