# Generated by Django 2.2.7 on 2020-09-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='halt',
            table='halts',
        ),
    ]
