# Generated by Django 2.2.7 on 2020-09-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0002_auto_20200901_2059'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicle_garage_mapping',
            table='vehicle_garage_mappings',
        ),
        migrations.AlterModelTable(
            name='ward_contractor_mapping',
            table='ward_contractor_mappings',
        ),
    ]
