# Generated by Django 2.2.7 on 2020-09-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('swmadmin', '0005_auto_20200910_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='common.Ward'),
        ),
    ]
