# Generated by Django 2.2.7 on 2020-09-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0006_vehicle_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward_contractor_mapping',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swmadmin.Contractor'),
        ),
    ]
