# Generated by Django 2.2.7 on 2021-10-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0007_auto_20200916_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward_contractor_mapping',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Ward'),
        ),
    ]
