# Generated by Django 2.2.7 on 2021-10-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0008_auto_20211002_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('mc', 'Mini Compactor'), ('lc', 'Large Compactor'), ('scv', 'Small Compactor Vehicle'), ('sw', 'Sweeper Vehicle'), ('ww', 'Watch & Ward')], default='scv', max_length=10),
        ),
    ]
