# Generated by Django 2.2.7 on 2021-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0009_auto_20211018_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
