# Generated by Django 2.2.7 on 2021-11-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0010_auto_20211028_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_schedule',
            name='end',
            field=models.ForeignKey(limit_choices_to={'is_chkpst': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_route_schedules', to='swmadmin.Stop_station'),
        ),
        migrations.AddField(
            model_name='route_schedule',
            name='start',
            field=models.ForeignKey(limit_choices_to={'is_mlc': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_route_schedules', to='swmadmin.Stop_station'),
        ),
    ]
