# Generated by Django 2.2.7 on 2021-11-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0011_auto_20211123_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route_schedule',
            old_name='end',
            new_name='chkpst',
        ),
        migrations.RenameField(
            model_name='route_schedule',
            old_name='start',
            new_name='mlc',
        ),
    ]
