# Generated by Django 2.2.7 on 2022-01-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0012_auto_20211124_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_schedule',
            name='chkpst',
            field=models.ForeignKey(limit_choices_to={'is_chkpst': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='swmadmin.Stop_station'),
        ),
        migrations.AlterField(
            model_name='route_schedule',
            name='mlc',
            field=models.ForeignKey(limit_choices_to={'is_mlc': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='swmadmin.Stop_station'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Bmc_contractor'),
        ),
    ]
