# Generated by Django 2.2.7 on 2022-01-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0013_auto_20220113_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Bmc_contractor'),
        ),
    ]
