# Generated by Django 2.2.7 on 2022-02-15 13:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0015_ewd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewd',
            name='ewd_fence',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
