# Generated by Django 2.2.7 on 2022-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0016_auto_20220215_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('S', 'Sweaper'), ('N', 'Normal')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('mc', 'Mini Compactor'), ('lc', 'Large Compactor'), ('scv', 'Small Compactor Vehicle'), ('sw', 'Sweeper Vehicle'), ('ww', 'Watch & Ward'), ('dw', 'Dry Waste')], default='scv', max_length=10),
        ),
    ]
