# Generated by Django 2.2.7 on 2022-07-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swmadmin', '0017_auto_20220318_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Dog_Van', 'Dog_Van'), ('Break_Down', 'Break_Down'), ('Refuse_Compactor', 'Refuse_Compactor'), ('Bakayantra(JCB)', 'Bakayantra(JCB)'), ('Dumper', 'Dumper'), ('Refuse_Mini_Compactor', 'Refuse_Mini_Compactor'), ('Sumo', 'Sumo'), ('Bus', 'Bus'), ('Hearse', 'Hearse'), ('Ambulance', 'Ambulance'), ('Scorpio', 'Scorpio'), ('Bolero', 'Bolero'), ('Car', 'Car'), ('Water_Tanker', 'Water_Tanker'), ('Mobile_Medical_Opthalmic_Van', 'Mobile_Medical_Opthalmic_Van'), ('Raid_Van', 'Raid_Van'), ('Blood_Bank', 'Blood_Bank'), ('Dry_Waste_Tempo', 'Dry_Waste_Tempo'), ('Truck', 'Truck'), ('Cattle_Impound_Van', 'Cattle_Impound_Van'), ('Encrochment', 'Encrochment'), ('Mechanical_Power_Sweeper', 'Mechanical_Power_Sweeper'), ('Mak_Lifton(Tree_Cutting)', 'Mak_Lifton(Tree_Cutting)'), ('Wrecker', 'Wrecker'), ('HYVA_Prime_Mover', 'HYVA_Prime_Mover'), ('Cesspool_Tanker', 'Cesspool_Tanker'), ('Jeep', 'Jeep'), ('Ward_and_Watch', 'Ward_and_Watch'), ('Meatvan', 'Meatvan'), ('Small_Closed_Vehicle', 'Small_Closed_Vehicle'), ('Side_Loading_Compactor', 'Side_Loading_Compactor'), ('Tanker_Fire_Fighter', 'Tanker_Fire_Fighter'), ('Beach_Cleaning_Machine', 'Beach_Cleaning_Machine'), ('Steer_Skid_Loader', 'Steer_Skid_Loader'), ('Tractor_Trailer', 'Tractor_Trailer'), ('Insecticide_Vehicle', 'Insecticide_Vehicle'), ('AQMRL', 'AQMRL'), ('Compactor', 'Compactor')], default='SCV', max_length=100),
        ),
    ]
